#!/bin/sh
# This script is called by proxybound to resolve DNS names

# DNS server used to resolve names
DNS_SERVER=1.1.1.1


if [ $# = 0 ] ; then
	echo "	usage:"
	echo "		proxyresolv <hostname> "
	exit
fi


export LD_PRELOAD=libproxybound.so
dig $1 @$DNS_SERVER +tcp | awk '/A.+[0-9]+\.[0-9]+\.[0-9]/{print $5;}'
